package com.jar36.jchat.packet;

public interface Command {
    Short LOGIN_REQUEST = 0x1;
    Short LOGIN_RESPONSE = 0x2;
    Short LOGOUT_REQUEST = 0x3;
    Short MESSAGE_REQUEST = 0x4;
    Short SESSION_REQUEST = 0x5;

    char LOGIN_REQUEST_SUBFUNCTION_LOGIN = 0x1;
    char LOGIN_REQUEST_SUBFUNCTION_CREATE_USER = 0x2;
    char LOGIN_REQUEST_SUBFUNCTION_CHANGE_USERNAME = 0x3;
    char LOGIN_REQUEST_SUBFUNCTION_CHANGE_PASSWD = 0x4;
}
